SELECT TEAMS.Name AS TEAMNAME, COUNT(TEAMS.Name) AS TIMESCHAMPION, CONFERENCES.Name AS CONFERENCENAME
FROM TEAMS 
JOIN CONFERENCES USING (conferenceId)
JOIN SEASONS ON (SEASONS.championId=TEAMS.teamId)
GROUP BY TEAMNAME, CONFERENCENAME;